// Specific tips per topic ID
const TOPIC_TIPS = {
  // KYB — nové otázky 1-5, 11
  'kyb-1': [
    'Kybernetika = věda o řízení a komunikaci v systémech (Norbert Wiener).',
    'Aktiva: primární (znalosti, data) vs podpůrná (hardware, zaměstnanci).',
    'Bezpečnost = prevence + technická opatření + nápravné mechanismy.',
    'GDPR chrání osobní údaje — zmiň co jsou osobní údaje (jméno, IP, email).',
    'Tři roviny ochrany dat: preventivní (GDPR), technická (NIS2, ZKB), nápravná (zákoník).',
  ],
  'kyb-2': [
    'Fyzická bezpečnost: kabely do lišt/zdí, patch panel v zamčeném racku.',
    'Softwarová bezpečnost: firewall, antimalware, aktualizace, VPN.',
    'Anonymita na internetu neexistuje — každá VPN má logy (log management).',
    'Firemní politika: složitost hesel, práva uživatelů, přístupy do místností.',
    'Zmiň rozdíl: pasivní prvky (kabely) vs aktivní prvky (switche, routery).',
  ],
  'kyb-3': [
    'Kybernetická hrozba ≠ síťová hrozba — kybernetická zahrnuje i lidský faktor.',
    'Typy útoků: phishing, ransomware, DDoS, MitM, social engineering.',
    'Ochrana: aktualizace, zálohy (3-2-1 pravidlo), silná hesla, MFA.',
    'Ransomware: šifruje data a žádá výkupné — segmentace sítě omezuje šíření.',
    'Social engineering útočí na lidi, ne na techniku — vzdělávání je klíčová obrana.',
  ],
  'kyb-4': [
    'Revitalizace = audit → plán → fyzická obnova → konfigurace → testování.',
    'Začni analýzou: fyzický stav kabeláže, měření propustnosti, bezpečnostní audit.',
    'Fyzická část: výměna kabeláže (Cat6/Cat6A), nové switche, access pointy.',
    'Logická část: VLAN segmentace, firewall pravidla, aktualizace firmware.',
    'Dokumentace je povinná — síťová mapa, IP tabulka, konfigurace zařízení.',
  ],
  'kyb-5': [
    'Aktualizace opravují zranitelnosti (CVE) — bez nich je systém snadný cíl.',
    'SIEM = Security Information and Event Management — centrální monitoring logů.',
    'IDS (detekce) vs IPS (prevence) — IPS může automaticky blokovat hrozby.',
    'Patch management: testování záplat před nasazením do produkce.',
    'Monitoring: sledování anomálií v síťovém provozu, neobvyklé přihlášení.',
  ],
  'kyb-11': [
    'Fyzická bezpečnost OS: zamčená serverovna, rack, Kensington lock na notebooky.',
    'Softwarová bezpečnost: aktuální OS + ovladače, firewall, antimalware, VPN.',
    'Autentizace: heslo, token, biometrika, dvoufázové ověření (2FA/MFA).',
    'Princip nejmenších oprávnění: uživatel má jen ta práva, která nutně potřebuje.',
    'Zmiň rozdíl: autentizace (kdo jsi?) vs autorizace (co smíš?).',
  ],
  'kyb-6': [
    'Klasifikace dat: veřejná → interní → důvěrná → tajná — vždy uveď příklady.',
    'Šifrování: AES-256 pro symetrické, RSA pro asymetrické — základ ochrany dat.',
    'Zálohy: pravidlo 3-2-1 — 3 kopie, 2 různá média, 1 mimo lokalitu.',
    'RTO (jak rychle obnovit) vs RPO (kolik dat ztratit) — klíčové metriky obnovy.',
    'DLP systémy zabraňují úniku dat — monitorují e-mail, USB, tisk.',
  ],
  'kyb-7': [
    'Steganografie skrývá existenci zprávy, kryptografie skrývá její obsah — klíčový rozdíl.',
    'Symetrická kryptografie: stejný klíč pro šifrování i dešifrování (AES-256).',
    'Asymetrická kryptografie: veřejný klíč šifruje, soukromý dešifruje (RSA, ECC).',
    'Hašovací funkce jsou jednosměrné — SHA-256 pro integritu, bcrypt pro hesla.',
    'LSB steganografie: skrývání dat v nejméně významných bitech pixelů obrázku.',
  ],
  'kyb-8': [
    'Autorský zákon č. 121/2000 Sb. — dílo vzniká okamžikem vytvoření, bez registrace.',
    'EULA vs GNU-GPL: EULA = právo užívat, GPL = právo upravovat a šířit.',
    'ZKB (zákon č. 181/2014 Sb.) — povinnosti pro provozovatele kritické infrastruktury.',
    'NÚKIB = Národní úřad pro kybernetickou a informační bezpečnost — hlásí se mu incidenty.',
    'Trestní zákoník § 230 — neoprávněný přístup k počítačovému systému je trestný čin.',
  ],
  'kyb-9': [
    'NÚKIB (ČR) vs ENISA (EU) — národní vs evropská agentura pro kybernetickou bezpečnost.',
    'CERT vs CSIRT: oba reagují na incidenty — CSIRT.CZ provozuje CZ.NIC, GovCERT.CZ provozuje NÚKIB.',
    'SOC = Security Operations Center — 24/7 monitoring bezpečnostních událostí.',
    'CISO = Chief Information Security Officer — nejvyšší odpovědná osoba za bezpečnost.',
    'Bug bounty programy: legální způsob, jak etičtí hackeři hlásí zranitelnosti za odměnu.',
  ],
  'kyb-10': [
    'Začni rozdílem: desktopový OS slouží uživateli, serverový poskytuje služby ostatním.',
    'Zmiň konkrétní příklady: Windows 11 vs Windows Server 2022, Ubuntu Desktop vs Ubuntu Server.',
    'Vysvětli pojem "role" u serverového OS — DHCP, DNS, AD, File server.',
    'Popiš strukturu adresářů Linuxu (/bin, /etc, /home) a Windows (C:\\Windows, Program Files).',
    'Zmínit GNU-GPL vs EULA licenci vždy boduje — ukazuje přehled.',
  ],
  'kyb-12': [
    'Zdůrazni: elektromagnetické vlny se šíří ve vakuu, NE vzduchem — komise to ráda slyší.',
    'Rozlišuj licenční a bezlicenční pásma — ČTÚ vydává povolení pro licenční.',
    'Projdi typy antén: směrová (Yagi) na dlouhé vzdálenosti, všesměrová pro domácnost.',
    'Zabezpečení: WPA3 + Radius server + MAC filtr = nejlepší kombinace.',
    'Zmiň Li-Fi jako zajímavost — přenos dat světlem, experimentální technologie.',
  ],
  'kyb-13': [
    'Procesor: RISC vs CISC — RISC má redukovanou sadu, CISC kompletní.',
    'RAM: vysvětli rozdíl SIMM/DIMM a generace DDR1–DDR5.',
    'Zdroj: barvy konektorů (žlutá +12V, červená +5V, černá zem) — komise to miluje.',
    'Tiskárny: jehličková = nezničitelná záloha, laserová = rychlost, inkoustová = kvalita.',
    'Základní deska: severní můstek (CPU, RAM, GPU) vs jižní můstek (USB, SATA, zvuk).',
  ],
  'kyb-14': [
    'Fyzická vrstva: NIC tvoří bity, repeater zesiluje, hub rozbočuje (ale způsobuje kolize).',
    'Linková vrstva: switch pracuje s MAC adresami, bridge spojuje dvě sítě.',
    'Metody switche: Store-and-forward (pomalejší, spolehlivější) vs Cut-through (rychlejší).',
    'Hub vs Switch: hub posílá všem = kolize + bezpečnostní riziko, switch posílá přímo.',
    'Port mirroring: zrcadlení MAC adresy mezi switchem a síťovým rozhraním.',
  ],
  'kyb-15': [
    'ISO/OSI má 7 vrstev, TCP/IP má 4 — TCP/IP je praktický, ISO/OSI teoretický.',
    'Pamatuj si: Fyzická=bity, Linková=rámce, Síťová=pakety, Transportní=segmenty.',
    'Na transportní vrstvě se rozhoduje TCP (spolehlivý) nebo UDP (rychlý, nespolehlivý).',
    'Zmiň konkrétní protokoly: HTTP na aplikační, IP na síťové, Ethernet na linkové.',
    'Model probíhá dvakrát — jednou na odesílateli (shora dolů), jednou na příjemci (zdola nahoru).',
  ],
  'kyb-16': [
    'Definice: propojení 2+ zařízení za účelem sdílení dat, hardware a komunikace.',
    'P2P vs Client-Server: P2P pro domácnosti, C-S pro firmy s centrální správou.',
    'Topologie: Star je nejběžnější, Bus se nepoužívá, Ring je jako Bus se spojenými konci.',
    'Velikosti: PAN (Bluetooth), LAN (škola/firma), MAN (univerzita), WAN (internet).',
    'Výhody Client-Server: centrální správa, vysoké zabezpečení, pokročilé služby.',
  ],
  'kyb-17': [
    'Bezpečnost = předcházení rizikům pomocí zásad, legislativy a technických opatření.',
    'Fyzická bezpečnost: kabely do zdí/lišt, rackové skříně, Kensington lock na notebooky.',
    'Softwarová: firewall, antimalware, pravidelné aktualizace (up-to-date).',
    'Anonymita na internetu neexistuje — VPN má logy, zero-trust VPN je nejbezpečnější.',
    'Firemní politika: složitost hesel, práva a oprávnění, přístupy do místností.',
  ],
  'kyb-18': [
    'IP adresa = logická adresa, MAC = fyzická. IP se mění, MAC je pevná v kartě.',
    'Prefix /24 = maska 255.255.255.0 = 254 klientů v síti.',
    'Třídy: A (0-127, /8), B (128-191, /16), C (192-223, /24).',
    'Statické vs dynamické přidělování: DHCP automaticky, APIPA jako záloha (169.254.x.x).',
    'Privátní IP se může opakovat globálně, veřejná je unikátní na celém internetu.',
  ],
  'kyb-19': [
    'Segmentace = rozdělení sítě na izolované části pro bezpečnost a přehlednost.',
    'Fyzická segmentace: vlastní kabeláž pro každý segment — maximální bezpečnost, ale drahé.',
    'VLAN: virtuální rozdělení pomocí L3 switche — flexibilní, levné, nejběžnější.',
    'Trunk port komunikuje ve více VLAN, Access port jen v jedné (koncová zařízení).',
    'VLAN hopping: bezpečnostní riziko — switch spoofing a double tagging, řeší správná konfigurace.',
  ],
  'kyb-20': [
    'POP3 (110) stahuje a maže ze serveru, IMAP4 (143) synchronizuje — IMAP je modernější.',
    'SMTP (25) odesílá, POP3/IMAP přijímají — tři typy programů: MUA, MTA, MDA.',
    'DHCP: Discover → Offer → Request → ACK — čtyři kroky přidělení IP adresy.',
    'DNS: překlad doménového jména na IP, nikdy naopak. Root servery je jen 13 (a-m).',
    'HTTP (80) vs HTTPS (443) — zámeček v prohlížeči = certifikát = ověřená identita.',
  ],

  // PRG
  'prg-1': [
    'HTML = HyperText Markup Language, vznikl 1990 pro CERN, dnes HTML5.',
    'Párové tagy (<body>...</body>) vs nepárové (<br>) — vždy uveď příklad.',
    'JavaScript je klientský skript — zpracovává ho prohlížeč, ne server.',
    'SEO: rychlost, responzivita, obsah, zpětné odkazy — čím lepší, tím výše ve vyhledávači.',
    'Zmiň WYSIWYG editory (WordPress) jako alternativu k ručnímu psaní HTML.',
  ],
  'prg-2': [
    'CSS = Cascading Style Sheets — odděluje vzhled od struktury HTML.',
    'Kaskáda: inline > internal > external — čím specifičtější, tím vyšší priorita.',
    'Box model: content → padding → border → margin — základ layoutu.',
    'Flexbox pro 1D layout, Grid pro 2D — obojí je dnes standard.',
    'Responzivita: media queries (@media) přizpůsobují styl velikosti obrazovky.',
  ],
  'prg-3': [
    'Dynamické stránky: obsah se generuje na serveru (PHP, ASP) nebo klientovi (JS).',
    'Server-side: PHP generuje HTML na serveru, klient dostane hotovou stránku.',
    'Client-side: JavaScript mění DOM v prohlížeči bez reloadu stránky.',
    'AJAX: asynchronní komunikace se serverem bez obnovení celé stránky.',
    'Zmiň rozdíl: statická stránka = stejná pro všechny, dynamická = personalizovaná.',
  ],
  'prg-8': [
    'Databáze = organizovaná kolekce dat. Relační DB používá tabulky s relacemi.',
    'Primární klíč (PK) jednoznačně identifikuje záznam, cizí klíč (FK) odkazuje na jiný.',
    'Normalizace: 1NF, 2NF, 3NF — odstraňuje redundanci a závislosti.',
    'ER diagram: entity, atributy, vztahy — základ návrhu databáze.',
    'Zmiň ACID vlastnosti transakcí: Atomicity, Consistency, Isolation, Durability.',
  ],
  'prg-9': [
    'SQL = Structured Query Language — jazyk pro práci s relačními databázemi.',
    'DDL (CREATE, ALTER, DROP) vs DML (SELECT, INSERT, UPDATE, DELETE).',
    'JOIN: INNER (průnik), LEFT/RIGHT (všechny z jedné strany), FULL OUTER.',
    'WHERE filtruje záznamy, GROUP BY seskupuje, HAVING filtruje skupiny.',
    'Index zrychluje vyhledávání, ale zpomaluje zápis — kompromis výkonu.',
  ],
  'prg-11': [
    'C# je silně typovaný, objektově orientovaný jazyk od Microsoftu (.NET).',
    'Datové typy: int, double, string, bool, char — vždy uveď příklad použití.',
    'Hodnotové typy (int, struct) vs referenční typy (class, string) — rozdíl v paměti.',
    'Nullable typy: int? umožňuje hodnotu null — důležité pro databázové operace.',
    'Zmiň var pro implicitní typování — kompilátor typ odvodí sám.',
  ],
  'prg-12': [
    'OOP: třída = šablona, objekt = instance třídy — vždy uveď konkrétní příklad.',
    'Dědičnost: potomek přebírá vlastnosti rodiče, může je rozšířit nebo přepsat.',
    'Zapouzdření: skrývání implementace pomocí přístupových modifikátorů.',
    'Polymorfismus: stejná metoda se chová různě podle typu objektu (override).',
    'Skládání vs dědění: "má" vs "je" — auto HAS engine, sportovní auto IS auto.',
  ],
  'prg-13': [
    'Atributy = proměnné třídy (fields). Vlastnosti (properties) = get/set přístup.',
    'Modifikátory: public (všude), private (jen třída), protected (třída + potomci), internal.',
    'Property s get/set umožňuje validaci při přiřazení hodnoty.',
    'Auto-property: public string Name { get; set; } — zkrácený zápis.',
    'Readonly atribut lze nastavit jen v konstruktoru — pro neměnné hodnoty.',
  ],
  'prg-14': [
    'Konstruktor = speciální metoda volaná při vytvoření objektu, stejné jméno jako třída.',
    'Bezparametrický konstruktor: new Auto() — výchozí hodnoty.',
    'Parametrický konstruktor: new Auto("BMW", 2020) — inicializace s hodnotami.',
    'Přetížení: více konstruktorů s různými parametry — this() volá jiný konstruktor.',
    'Pokud nedefinuješ konstruktor, C# vytvoří výchozí bezparametrický automaticky.',
  ],
  'prg-15': [
    'Metoda = pojmenovaný blok kódu s návratovým typem, jménem a parametry.',
    'void = metoda nic nevrací, jinak musí obsahovat return správného typu.',
    'Přetížení metod: stejné jméno, různé parametry — kompilátor vybere správnou.',
    'Statická metoda patří třídě, ne instanci — volá se přes název třídy.',
    'ref a out parametry: ref předává referenci, out musí být v metodě přiřazen.',
  ],
  'prg-16': [
    'WinForms = framework pro tvorbu desktopových aplikací s grafickým rozhraním.',
    'Základní prvky: Button, TextBox, Label, ComboBox, ListBox, CheckBox, RadioButton.',
    'Každý prvek má vlastnosti (Text, Size, Location) a události (Click, TextChanged).',
    'Designer v Visual Studiu umožňuje drag-and-drop tvorbu UI.',
    'Zmiň rozdíl mezi modálním (ShowDialog) a nemodalním (Show) oknem.',
  ],
  'prg-17': [
    'Událost (event) = oznámení, že nastalo něco zajímavého (klik, změna textu).',
    'Delegát = typově bezpečný ukazatel na metodu — základ událostí v C#.',
    'EventHandler je standardní delegát pro události: (object sender, EventArgs e).',
    'Přidání handleru: button.Click += MyMethod; Odebrání: button.Click -= MyMethod;',
    'Lambda výraz jako handler: button.Click += (s, e) => { /* kód */ };',
  ],
  'prg-18': [
    'BlueJ = výukové IDE pro Javu, vizualizuje třídy a jejich vztahy.',
    'Uzlový seznam: každý uzel obsahuje data a odkaz na další uzel.',
    'Jednosměrný: uzel zná jen následníka. Obousměrný: zná i předchůdce.',
    'Operace: přidání na začátek O(1), na konec O(n), vyhledání O(n).',
    'Výhoda oproti poli: dynamická velikost, snadné vkládání/mazání uprostřed.',
  ],
  'prg-19': [
    'Utility: třída se statickými metodami, nelze instanciovat — Math, Arrays.',
    'Singleton: zajišťuje existenci právě jedné instance — getInstance() metoda.',
    'Tovární metoda: statická metoda místo konstruktoru pro vytváření objektů.',
    'Enum: výčtový typ pro pojmenované konstanty — DayOfWeek.Monday.',
    'Návrhové vzory řeší opakující se problémy — jsou to osvědčené recepty.',
  ],
  'prg-20': [
    'Interface = kontrakt — třída musí implementovat všechny metody rozhraní.',
    'Servant: objekt poskytující funkcionalitu jiným objektům přes interface.',
    'Generické třídy: List<T>, Dictionary<K,V> — typová bezpečnost bez castování.',
    'Messenger: vzor pro komunikaci mezi objekty bez přímé závislosti.',
    'Interface vs abstraktní třída: interface = čistý kontrakt, abstraktní = částečná implementace.',
  ],
  'prg-4': [
    'Robot = autonomní stroj schopný vykonávat úkoly v reálném světě.',
    'Senzory (vstup) → Řídicí jednotka (zpracování) → Aktuátory (výstup).',
    'Typy robotů: průmyslové, servisní, mobilní, humanoidní, kolaborativní (coboti).',
    'Stupně volnosti (DOF): počet nezávislých pohybů robota.',
    'Zmiň etiku robotiky — Asimovovy zákony jako historický kontext.',
  ],
  'prg-5': [
    'IoT = Internet of Things — propojení fyzických zařízení s internetem.',
    'Architektura: zařízení → gateway → cloud → aplikace.',
    'Protokoly: MQTT (lehký, pro IoT), HTTP, CoAP.',
    'Bezpečnost IoT je kritická — slabá hesla, nešifrovaná komunikace jsou rizika.',
    'Příklady: chytrá domácnost, průmysl 4.0, smart city, wearables.',
  ],
  'prg-6': [
    'Programování robotů: sekvenční, podmíněné, cyklické instrukce.',
    'Senzory poskytují zpětnou vazbu — robot reaguje na prostředí.',
    'Simulace před nasazením: testování v virtuálním prostředí šetří čas a peníze.',
    'Zmiň konkrétní platformy: Arduino, Raspberry Pi, ROS (Robot Operating System).',
    'Ladění (debugging) robotů je složitější než softwaru — fyzické prostředí přidává proměnné.',
  ],
  'prg-7': [
    'Hardware robota: aktuátory (motory, serva), senzory (IR, ultrazvuk, kamera), řídicí jednotka.',
    'Software: firmware (nízkoúrovňový), middleware, aplikační vrstva.',
    'Komunikace: sériová (UART), I2C, SPI, CAN bus v průmyslu.',
    'Napájení: baterie (mobilní roboti), kabelové napájení (průmyslové).',
    'Zmiň rozdíl mezi open-source (Arduino, ROS) a proprietárními platformami.',
  ],
  'prg-10': [
    'Algoritmus = konečná posloupnost kroků řešící daný problém.',
    'Vlastnosti: konečnost, určitost, vstup/výstup, efektivnost.',
    'Vývojový diagram: ovál (start/konec), obdélník (operace), kosočtverec (podmínka).',
    'Složitost: O(1) konstantní, O(n) lineární, O(n²) kvadratická, O(log n) logaritmická.',
    'Rekurze: funkce volá sama sebe — vždy musí mít základní případ (base case).',
  ],

  // Nové knihy z 00 Škola
  'ces-kulicka': [
    'Maupassant: francouzský realismus/naturalismus, 2. polovina 19. století.',
    'Kulička = prostitutka, která je morálně nadřazená "slušné" společnosti — ironie.',
    'Téma: pokrytectví buržoazie, válka (prusko-francouzská), lidská sobeckost.',
    'Zmiň naturalistické prvky: přesný popis reality bez příkras.',
    'Kulička pomůže ostatním, ti ji pak opovrhují — tragická ironie příběhu.',
  ],
  'ces-lakomec': [
    'Molière: francouzský klasicismus, 17. století, komedie charakterů.',
    'Harpagon = archetyp lakomce, jeho chamtivost ničí vztahy i vlastní rodinu.',
    'Klasicistní pravidlo tří jednot: místo, čas, děj — vše se odehraje za jeden den.',
    'Téma: peníze jako modla, která nahrazuje lidské hodnoty.',
    'Zmiň, že Molière psal pod pseudonymem — "nízké" drama nesmělo nést jeho jméno.',
  ],
  'ces-my-deti-ze-stanice-zoo': [
    'Christiane F.: autobiografická zpověď, dokumentární literatura.',
    'Téma: drogová závislost, prostituce, rozpad rodiny, Berlín 70. let.',
    'Dílo vzniklo z rozhovoru pro časopis Stern — reportáž se stala knihou.',
    'Zmiň společenský dopad: změnilo pohled na mladistvé závislé v Německu.',
    'Naturalistický styl: přímý, bez příkras — šokující právě proto, že je pravdivý.',
  ],
  'ces-r-u-r': [
    'Čapek: R.U.R. = Rossumovi Univerzální Roboti — slovo "robot" pochází z tohoto díla.',
    'Téma: technologický pokrok bez etiky, vzpoura robotů, ztráta lidskosti.',
    'Roboti jsou zpočátku nástroje — pak získají city a vzbouří se.',
    'Zmiň, že Čapek předvídal AI a automatizaci — dílo je stále aktuální.',
    'Zakončení: Helena a Primus = nový Adam a Eva — naděje na nový začátek.',
  ],
  'ces-v-zamku-a-podzamci': [
    'Němcová: realistická povídka, kontrast šlechtického a venkovského světa.',
    'Téma: sociální nerovnost, útlak poddaných, síla prostého člověka.',
    'Paní kněžna vs. venkovský lid — Němcová sympatizuje s chudými.',
    'Zmiň autobiografické prvky — Němcová znala prostředí z dětství v Ratibořicích.',
    'Dílo je méně známé než Babička, ale ukazuje kritičtější pohled Němcové.',
  ],
  'ces-zdravy-nemocny': [
    'Molière: klasicistní komedie, satira na medicínu 17. století.',
    'Argan předstírá nemoc, aby ovládal rodinu a nemusel čelit realitě.',
    'Téma: hypochondrie, lékařský šarlatánismus, rodinné vztahy.',
    'Molière zemřel při čtvrtém představení této hry — tragická ironie.',
    'Zmiň klasicistní rysy: typy postav (lakomec, pokrytec), morální ponaučení.',
  ],
  'ces-1984': [
    'Orwell napsal 1984 jako varování před totalitarismem — zmiň kontext studené války.',
    'Klíčové pojmy: Velký bratr, Newspeak, doublethink, Ministerstvo pravdy — vysvětli je.',
    'Téma: totalita ničí individualitu, jazyk kontroluje myšlení.',
    'Porovnej s Farmou zvířat — obě díla jsou alegorií na sovětský komunismus.',
    'Hlavní postava Winston Smith = symbol odporu, který je nakonec zlomen.',
  ],
  'ces-babi-ka': [
    'Babička = idealizovaný obraz venkovského života, nostalgie Němcové po dětství.',
    'Literární směr: realismus s romantickými prvky, národní obrození.',
    'Babička není jen postava — je symbolem moudrosti, tradic a národní identity.',
    'Zmiň autobiografické prvky — Němcová vychází z vlastních vzpomínek.',
    'Dílo vzniklo jako vzpomínka na zemřelou babičku — emocionální kontext boduje.',
  ],
  'ces-bylo-n-s-p-t': [
    'Poláček zachytil dětský svět z pohledu dítěte — humor pramení z naivity vypravěče.',
    'Ich-forma: Petr Bajza vypráví — jeho pohled je omezený, ale autentický.',
    'Téma: bezstarostné dětství, kamarádství, malá města v meziválečném Československu.',
    'Zmiň tragický osud autora — Poláček zahynul v koncentračním táboře.',
    'Humor je jemný, situační — ne vulgární. Dílo je láskyplné, ne satirické.',
  ],
  'ces-b-je-n-l-ta-pod-psa': [
    'Viewegh = jeden z nejčtenějších českých autorů 90. let, postmoderní prvky.',
    'Retrospektivní kompozice: dospělý Kvido vzpomíná na dětství za komunismu.',
    'Téma: jak komunismus deformoval normální rodinný život.',
    'Humor jako obranný mechanismus — rodina se směje, aby neplákal.',
    'Zmiň intertextualitu — Viewegh odkazuje na jiná literární díla.',
  ],
  'ces-b-l-nemoc': [
    'Čapek napsal Bílou nemoc 1937 jako varování před fašismem — historický kontext!',
    'Drama o třech dějstvích: doktor Galén vs. Maršál — věda vs. moc.',
    'Bílá nemoc = alegorie na fašismus, který ničí bez rozdílu.',
    'Galén odmítá léčit bohaté a mocné — etická otázka: je to správné?',
    'Tragické zakončení: Galén je ušlapán davem — ironie, dav zničí svou jedinou naději.',
  ],
  'ces-div-b-ra': [
    'Němcová: Divá Bára = silná, svobodná žena v době, kdy to bylo nepřijatelné.',
    'Téma: předsudky společnosti vs. přirozená svoboda člověka.',
    'Bára je "divá" jen podle ostatních — ve skutečnosti je laskavá a statečná.',
    'Romantické prvky: příroda, silná individualita, konflikt jedince se společností.',
    'Zmiň feministický podtext — Němcová sama bojovala za práva žen.',
  ],
  'ces-farma-zv-at': [
    'Alegorie na Ruskou revoluci a stalinismus — zvířata = lid, prasata = bolševici.',
    'Napoleon = Stalin, Kuliš = Trockij, pan Jones = car Mikuláš II.',
    'Klíčová věta: "Všechna zvířata jsou si rovna, ale některá jsou si rovnější."',
    'Téma: revoluce, která zradí své ideály a vytvoří novou tyranii.',
    'Orwell byl socialista, ale kritizoval sovětský komunismus — důležitý kontext.',
  ],
  'ces-harry-potter-a-k-men-mudrc-': [
    'Rowlingová: fantasy žánr, bildungsroman (román o dospívání).',
    'Téma: dobro vs. zlo, přátelství, odvaha, síla lásky.',
    'Harry = sirotek, který nezná svůj původ — klasický hrdinský archetyp.',
    'Zmiň světový úspěch — přeloženo do 80+ jazyků, fenomén popkultury.',
    'Literární prostředky: magie jako metafora pro dospívání a hledání identity.',
  ],
  'ces-krakatit': [
    'Čapek: Krakatit = varování před zneužitím vědy a techniky.',
    'Prokop vynalezne výbušninu Krakatit — ale nedokáže ji ochránit před mocnými.',
    'Téma: odpovědnost vědce za své vynálezy, moc vs. etika.',
    'Expresionistické prvky: sny, halucinace, nejasná hranice reality.',
    'Zmiň paralelu s atomovou bombou — Čapek předvídal nebezpečí vědeckého pokroku.',
  ],
  'ces-kr-l-l-vra': [
    'Havlíček Borovský: satirická báseň, ironie a humor jako zbraň proti tyranii.',
    'Král Lávra má oslí uši — tajemství, které nelze udržet.',
    'Alegorie: Lávra = František Josef I., kritika habsburské monarchie.',
    'Žánr: epická báseň s lyrickými prvky, humorná balada.',
    'Havlíček byl za svou tvorbu internován v Brixenu — zmiň jeho odvahu.',
  ],
  'ces-labyrint-sv-ta-a-r-j-srdce': [
    'Komenský: barokní alegorie, 17. století, exil po Bílé hoře.',
    'Poutník prochází světem (labyrintem) a hledá smysl — nenachází ho, dokud se neobrátí k Bohu.',
    'Téma: marnost světských věcí, útěcha ve víře.',
    'Zmiň historický kontext: Komenský psal v exilu po porážce na Bílé hoře 1620.',
    'Dílo je alegorické — každé povolání a stav společnosti je symbolicky zobrazeno.',
  ],
  'ces-m-j': [
    'Mácha: Máj = vrchol českého romantismu, 1836.',
    'Vilém = loupežník, který nevědomky zabil vlastního otce — tragický hrdina.',
    'Téma: smrt, láska, příroda, existenciální otázky.',
    'Příroda v Máji není kulisa — je aktivním účastníkem děje, zrcadlí emoce.',
    'Zmiň kontroverzi při vydání — dílo bylo odmítnuto, dnes je národní klenot.',
  ],
  'ces-obsluhoval-jsem-anglick-ho-kr-le': [
    'Hrabal: Jan Dítě = malý člověk s velkými sny, pikareskní román.',
    'Retrospektivní vyprávění: starý Dítě vzpomíná na svůj život.',
    'Téma: ctižádost, kolaborace, morální kompromisy, ztráta iluzí.',
    'Zmiň Hrabalův styl: "pábení" — proud vědomí, digrese, humor.',
    'Dítě se obohatí za protektorátu — morální otázka kolaborace s nacisty.',
  ],
  'ces-ost-e-sledovan-vlaky': [
    'Hrabal: Ostře sledované vlaky = novela z doby protektorátu.',
    'Miloš Hrma = mladý výpravčí, jeho dospívání probíhá za války.',
    'Téma: dospívání, hledání identity, válka jako absurdní pozadí.',
    'Zmiň filmovou adaptaci — Jiří Menzel, Oscara za nejlepší zahraniční film 1967.',
    'Hrabalův humor: tragické situace jsou podány s nadsázkou a ironií.',
  ],
  'ces-osudy-dobr-ho-voj-ka-vejka-za-sv-tov-v-lky': [
    'Hašek: Švejk = protiválečný román, satira na habsburskou armádu.',
    'Švejk: je hloupý, nebo chytrý? Tato otázka je záměrně nezodpovězena.',
    'Téma: absurdita války, byrokracie, neschopnost autorit.',
    'Dílo zůstalo nedokončeno — Hašek zemřel před dokončením.',
    'Zmiň, že Švejk se stal symbolem českého národního charakteru.',
  ],
  'ces-proces': [
    'Kafka: Proces = absurdní román, Josef K. je obviněn, aniž by věděl z čeho.',
    'Kafkaeska = pocit bezmoci vůči nepochopitelné autoritě — zmiň tento pojem.',
    'Téma: vina bez příčiny, odcizení, byrokracie jako nepřekonatelná síla.',
    'Kafka psal německy v Praze — zmiň jeho trojí odcizení (Žid, Němec, Pražan).',
    'Dílo vyšlo posmrtně — Kafka chtěl rukopisy zničit, přítel Max Brod je zachránil.',
  ],
  'ces-prom-na': [
    'Kafka: Řehoř Samsa se probudí jako brouk — ale rodina ho přijme jako zátěž.',
    'Proměna = alegorie na odcizení, ztrátu lidskosti, rodinné vztahy.',
    'Téma: co z nás dělá lidi? Rodina Řehoře ho opustí, když přestane být užitečný.',
    'Strohý, věcný styl — Kafka popisuje absurdní situaci jako by byla normální.',
    'Zmiň autobiografický prvek — Kafka sám se cítil jako břemeno pro rodinu.',
  ],
  'ces-romeo-a-julie': [
    'Shakespeare: Romeo a Julie = tragédie o lásce přemáhající nenávist rodů.',
    'Montekové vs. Kapuleti — rodinná nenávist jako příčina tragédie.',
    'Téma: láska, osud, nenávist, smrt — vše propojeno.',
    'Zmiň, že dílo je drama — bylo psáno pro divadlo, ne pro čtení.',
    'Tragická ironie: Romeo si myslí, že Julie je mrtvá — a ona se vzbudí pozdě.',
  ],
  'ces-sen-noci-svatoj-nsk-': [
    'Shakespeare: komedie s magickými prvky, les jako místo proměny.',
    'Čtyři milostné páry, elfové, řemeslníci — tři světy se prolínají.',
    'Téma: láska je iracionální, osud si hraje s lidmi.',
    'Puk = trickster, způsobuje chaos — ale vše dobře dopadne.',
    'Zmiň divadelní hru ve hře — řemeslníci hrají Pyrama a Thisbé.',
  ],
  'ces-slavnosti-sn-enek': [
    'Hrabal: povídkový soubor z Kerska, autobiografické prvky.',
    'Téma: obyčejný život, příroda, přátelství, radost z malých věcí.',
    'Hrabalův styl: "pábení" — volné asociace, humor, digrese.',
    'Zmiň, že Hrabal žil v Kersku — chata jako útočiště před civilizací.',
    'Dílo je oslavou prostého života — kontrast s velkou literaturou.',
  ],
  'ces-tyrolsk-elegie': [
    'Havlíček Borovský: autobiografická báseň o internaci v Brixenu 1851-1855.',
    'Téma: nesvoboda, tyranie, pokrytectví habsburské monarchie.',
    'Ironie a sarkasmus jako hlavní literární prostředky.',
    'Havlíček byl odvezen tajně v noci — zmiň tuto historickou událost.',
    'Elegie = žalozpěv, ale Havlíček ji naplnil hořkým humorem, ne pláčem.',
  ],
  'ces-vy-et-ov-n-ztr-ty-t-dn-knihy': [
    'Smoljak, Svěrák, Cimrman: absurdní komedie, divadlo Járy Cimrmana.',
    'Jára Cimrman = fiktivní génius, který vždy přišel o krok dřív než slavní.',
    'Téma: absurdita školního systému, byrokracie, lidská hloupost.',
    'Zmiň unikátní formát: seminář + divadelní hra — dvě části představení.',
    'Humor je intelektuální, slovní hříčky, absurdní situace — typicky český.',
  ],
  'ces-v-chova-d-vek-v-ech-ch': [
    'Viewegh: postmoderní román, ich-forma, autobiografické prvky.',
    'Jakub = spisovatel, který píše o svém vztahu s Kristýnou.',
    'Téma: láska, deprese, hledání smyslu, česká společnost po revoluci.',
    'Zmiň intertextualitu — Viewegh cituje jiné autory a díla.',
    'Název je ironický — dílo není o výchově dívek, ale o neschopnosti muže.',
  ],
  // Matematika — obecné tipy (fallback)
  'mat-general': [
    'Vždy uveď vzorec, pak postup, pak výsledek — komise hodnotí postup, ne jen výsledek.',
    'Nakresli graf nebo schéma kdykoli je to možné — vizualizace boduje.',
    'Zkontroluj definiční obor před řešením rovnice nebo nerovnice.',
    'U slovních úloh: pojmenuj proměnné, sestav rovnici, vyřeš, ověř v zadání.',
    'Zmiň speciální případy (D = 0, D < 0, parametr = 0) — ukazuje přehled.',
  ],
  'mat-0': [
    'Test UHK: 15 příkladů, ~60 minut — průměrně 4 minuty na příklad. Přeskoč těžké, vrať se.',
    'Nejčastější témata: logaritmy (definiční obory!), rovnice s odmocninami, mocniny, množiny.',
    'U rovnic s odmocninami VŽDY ověř kořeny dosazením — záporné kořeny jsou past.',
    'Logaritmus: log_a(x) existuje jen pro x > 0 a a > 0, a ≠ 1 — definiční obor je klíčový.',
    'Eliminace: i když nevíš postup, vyloučení 2–3 špatných odpovědí zvyšuje šanci na 50 %.',
  ],
  'mat-1': [
    'Výrok musí být pravdivý nebo nepravdivý — otázky a rozkazy nejsou výroky.',
    'Negace konjunkce: ¬(A ∧ B) = ¬A ∨ ¬B (De Morganovy zákony).',
    'Implikace A⇒B je nepravdivá jen když A je pravda a B je lež.',
    'Obecný výrok (∀x): negace je existenční (∃x: ¬P(x)) a naopak.',
    'Množinové operace: průnik ∩, sjednocení ∪, rozdíl \\, doplněk — vždy uveď příklad.',
  ],
  'mat-2': [
    'Číselné obory: ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ ⊂ ℂ — každý je podmnožinou dalšího.',
    'Dělitelnost: číslo a dělí b, pokud b = k·a pro nějaké celé k.',
    'Komplexní číslo: z = a + bi, kde i² = −1. Absolutní hodnota: |z| = √(a²+b²).',
    'Goniometrický tvar: z = r(cos φ + i·sin φ), kde r = |z|, φ = argument.',
    'Gaussova rovina: reálná osa = x, imaginární osa = y.',
  ],
  'mat-3': [
    'Lineární funkce: f(x) = ax + b. Sklon a = tangens úhlu s osou x.',
    'Soustava rovnic: sčítací metoda — vynásob rovnice tak, aby se jedna proměnná odečetla.',
    'Grafické řešení soustavy = průsečík přímek. Rovnoběžky = žádné řešení.',
    'Nerovnice: při násobení záporným číslem se obrací znaménko nerovnosti.',
    'Lineární lomená funkce: f(x) = (ax+b)/(cx+d) — asymptoty jsou klíčové.',
  ],
  'mat-4': [
    'Kvadratická rovnice: ax² + bx + c = 0. Diskriminant D = b² − 4ac.',
    'D > 0: dva různé reálné kořeny. D = 0: jeden dvojnásobný. D < 0: komplexní kořeny.',
    'Vietovy vzorce: x₁+x₂ = −b/a, x₁·x₂ = c/a — rychlá kontrola výsledku.',
    'Vrchol paraboly: V = [−b/(2a), −D/(4a)].',
    'Kvadratická nerovnice: nakresli parabolu, urči kde je nad/pod osou x.',
  ],
  'mat-12': [
    'Aritmetická posloupnost: aₙ = a₁ + (n−1)d. Součet: Sₙ = n(a₁+aₙ)/2.',
    'Geometrická posloupnost: aₙ = a₁·qⁿ⁻¹. Součet: Sₙ = a₁(qⁿ−1)/(q−1).',
    'Nekonečná geometrická řada konverguje jen pro |q| < 1: S = a₁/(1−q).',
    'Složené úročení: Kₙ = K₀·(1+p/100)ⁿ — základ finanční matematiky.',
    'Umořování: každá splátka = úrok + část jistiny. Zmiň anuitní splácení.',
  ],
  'mat-13': [
    'Kombinační číslo: C(n,k) = n! / (k!·(n−k)!) — počet k-prvkových podmnožin.',
    'Permutace bez opakování: P(n) = n! — pořadí n prvků.',
    'Variace bez opakování: V(n,k) = n!/(n−k)! — k prvků z n, záleží na pořadí.',
    'Binomická věta: (a+b)ⁿ = Σ C(n,k)·aⁿ⁻ᵏ·bᵏ.',
    'Pascalův trojúhelník: rychlý způsob výpočtu kombinačních čísel.',
  ],
  'mat-14': [
    'Pravděpodobnost: P(A) = počet příznivých / počet všech stejně možných výsledků.',
    'Jev jistý: P(Ω) = 1. Jev nemožný: P(∅) = 0.',
    'Nezávislé jevy: P(A∩B) = P(A)·P(B). Neslučitelné: P(A∪B) = P(A)+P(B).',
    'Aritmetický průměr, medián, modus — znát rozdíl a kdy který použít.',
    'Rozptyl a směrodatná odchylka měří variabilitu dat — vzorce jsou v tabulkách.',
  ],

  // Čeština — obecné tipy (fallback)
  'ces-general': [
    'Vždy začni: autor, název, rok vydání, literární směr a žánr.',
    'Popiš téma (o čem dílo je) vs motiv (opakující se prvek) vs myšlenku (poselství).',
    'Charakterizuj hlavní postavy — jejich vývoj v průběhu děje je klíčový.',
    'Zmiň historický a společenský kontext vzniku díla.',
    'Zakončit vlastním hodnocením díla je vždy plus — buď upřímný.',
  ],

  // Angličtina — obecné tipy (fallback)
  'ang-general': [
    'Začni odpověď obecnou větou k tématu, pak přejdi ke konkrétním příkladům.',
    'Používej spojovací výrazy: Furthermore, However, On the other hand, In my opinion...',
    'Pokud neznáš slovo, oppiš ho: "It\'s a thing that you use to..." — nekoukat do prázdna.',
    'Mluv v celých větách, ne jen jednoslovně — zkouška trvá 15 minut, musíš zaplnit čas.',
    'Příprava trvá 15 minut — napiš si 5-7 klíčových bodů, ne celé věty.',
    'U reálií (UK/USA/ČR) vždy zmiň: hlavní město, počet obyvatel, typ vlády, hlavní pamětihodnosti.',
  ],
};
function getTips(catId, topicId) {
  if (TOPIC_TIPS[topicId]) return TOPIC_TIPS[topicId];
  if (catId === 'ces') return TOPIC_TIPS['ces-general'];
  if (catId === 'mat') return TOPIC_TIPS['mat-general'] || [];
  if (catId === 'ang') return TOPIC_TIPS['ang-general'] || [];
  return [];
}
